image: node:15

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  script:
    - npm install
    - npm run build
    - npm run export
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master
